---
title: "Emergency Medical Plan"
# output: 
#   revealjs::revealjs_presentation:
#     self_contained: true
#     theme: black
#     transition: slide

format: 
  revealjs:
    theme: "moon"
    transition: "slide"
    
---

# Contact Information 📔

- **CCF On-Call Clinician**: Refer to the Center for Children and Families (CCF) On-Call Clinical Schedule in the Outlook calendar (access required).

# Key Contacts

## Our Team

- **Raul Gonzalez**, PhD, Professor, NPI #1356417596
    - 📱 305-501-xxxx
    - 📧 raul.gonzalezjr@fiu.edu
    - ☎️ 305-348-4921

- **Samuel Hawes**, PhD, Associate Research Professor, License #PY 10774 [Florida]
    - 📱 786-717-xxxx
    - 📧 shawes@fiu.edu
    - ☎️ 305-348-5439

- **Dr. Angela Laird**, PhD, Professor
    - 📱 210-355-xxxx
    - 📧 alaird@fiu.edu
    - ☎ ️office phone: 305 348-6737

- **Nicole Schat**, PhD, Associate Research Professor, License #PY 9541 [Florida]
    - 📱 573-201-xxxx
    - 📧 nschatz@fiu.edu
    - ☎️ office phone: 305-348-0663

## Emergency Contacts

- **Florida Department of Children and Families Abuse Hotline & Adult Protective Services**: [1-800-962-2873](https://reportabuse.dcf.state.fl.us/) or fax 1-800-914-0004

- **FIU Police**: (305) 348-5911 (or 7-5911 from an FIU phone)

- **Emergency**: 911

- **Miami Information & Referral, 24/7**: Dial 211 or visit [Switchboard Miami](http://switchboardmiami.org/)

---

## Responsible Clinician

|                | Psychiatric | Neurological | BP/Blood alerts |
|----------------|:-----------:|:------------:|:---------------:|
| Raul Gonzalez  |      X      |      X       |        X        |
| Samuel Hawes   |      X      |              |                 |
| Nicole Schatz  |             |              |        X        |

*see also CCF On-Call Clinician calendar

---

# Confidentiality Limitations 🔐

<div class="important">
 
"Most of what you say is confidential. The few exceptions include..."

- A child has been abused
- An elder adult or dependent adult has been abused
- You have plans to seriously harm yourself
- You intend to seriously harm someone else
- You are in immediate danger for another reason

"In those cases, I may need to break this confidentiality and inform the right people, so we can make sure everyone is safe."

</div>

---

<div class="important">

# Responsible Clinician Involvement

- **Primary Contact**: On-Call Clinician as per schedule.
  - 🚑 **Backup**: Dr. Hawes (or Dr. Gonzalez) in the absence of the On-Call Clinician.
  - 📝 **Post-Incident**: Complete and submit an Incident Report Form to Dr. Hawes (or Dr. Gonzalez).

### Incident Response Procedure

1. **Assessment**: Staff assessors (Research Assistants/Associates) identify and gather details on potential imminent risk situations.
2. **Communication**: Information relayed to the responsible clinician for further evaluation.
3. **Determination**: The responsible clinician will make the final determination on the participant's risk level and necessary actions.
4. **Virtual Protocols**: Ensure a secondary communication method (e.g., personal phone) for uninterrupted contact during virtual assessments.
5. **Support**: Immediate briefing and additional support from Dr. Hawes (or Drs. Gonzalez or Laird).

</div>
---

<div class="dense-content">

# 🛑 Abuse of Child, Elder, or Dependent Adult

- **Types of Abuse**: Physical, emotional, financial, sexual exploitation, or neglect.
- **Initial Assessment & Reporting**: Follow site’s EMP and ABCD Site SOP for Youth KSADS PTSD upon a KSADS PTSD alert.
- **Information to Collect**: Victim & Perpetrator Details, Abuse Description, Immediate Danger assessment.
- **Consultation & Decision Making**: Determine with the responsible clinician if notifying individuals of the report could increase risk.
- **Reporting Process**: Contact (800-962-2873) or visit [Florida Abuse Hotline](https://reportabuse.dcf.state.fl.us/).

</div>

---

# 🛑 Suicidality Response Protocol

### Alert and Disclosure Response
- **Alerts**: Immediate action on KSADS, ASR, CBCL alerts indicating suicidal ideation.
- **In-Person Disclosure**: Assess PLAN, INTENT, MEANS, and LOCATION upon disclosure of intent to self-harm.
- **Remote Disclosure**: Maintain contact and use a secondary device to call 911 for immediate suicide threats.

### Communication Guidelines
- **Inform Participant**: Necessary disclosure to ABCD supervisors for follow-up.
- **Confidentiality**: Break confidentiality if needed to ensure safety, informing the participant of the action.

### Documentation
- **Incident Report**: Document all disclosures, actions taken, and follow-up in an Incident Report Form.

---

# 🛑 Intent to Harm Others and Homicidal Ideation
  ### Alert and Disclosure Response
- **Alerts**: Act on any KSADS, ASR, CBCL alerts suggesting harm to others.
- **In-Person Disclosure**: Verify PLAN, INTENT, MEANS, and gather Potential Victim and Perpetrator Information.
- **Remote Disclosure**: Do not disconnect; use another device to contact emergency services for imminent threats.

### Protective Actions
- **Immediate Notification**: Inform potential victims and law enforcement if there's a credible threat.
- **Clinician Consultation**: If unavailable, contact Dr. Gonzalez or Dr. Hawes for guidance.

### Documentation and Confidentiality
- **Duty to Warn**: Notify authorities and intended victims as required, considering the need to break confidentiality.
- **Incident Reporting**: Complete detailed documentation of the threat, response, and any advisories given.

---

# 🧠 ABCD Neuroradiology Report and MRI Findings

- **Recipient**: Dr. Raul Gonzalez
- **Consultant**: Dr. Leo Sugrue (leo.sugrue@ucsf.edu)
- **Procedure**: Immediate notification of Dr. Gonzalez through ABCD DAIC for incidental findings.
- **Follow-Up**: Dr. Gonzalez assesses clinical significance and communicates with families.
- **Documentation**: Findings and actions documented in ABCD REDCap and FIU notes.

---

# 🛑 Blood Pressure and Laboratory Incidental Findings

- **Alert Recipient**: Dr. Raul Gonzalez
- **Consultation**: With Dr. Suzie Noronha for significant findings.
- **Family Communication**: Discuss findings with families and recommend follow-up.
- **Documentation**: Record in ABCD REDCap and include in FIU notes.


---

# 🚑 Medical Emergency Protocol

- **Initial Response**: Contact the responsible clinician for evaluation.
- **Parent/Guardian Notification**: Inform immediately, depending on the severity.
- **Emergency Services**: Call 911 for serious injuries.
- **Documentation**: Complete a report detailing the emergency and response.

---

# ⚠️ Other Imminent Risks

- **Assessment**: Staff assessors to gather detailed information on the risk.
- **Clinician Notification**: Contact Dr. Gonzalez or Dr. Hawes for risk evaluation.
- **Confidentiality**: May be broken if necessary to prevent harm.
- **Documentation**: Incident report to be filled and included in the consent file.

---

# 🖥️ Remote or Virtual Visits

- **Preparation**: Verify participant's location and contact numbers.
- **Emergency Protocol**: Follow in-person visit procedures for any emergencies.
- **Clinician Contact**: Ensure availability of two phone lines for immediate communication.


