---
title: "Manuscript Title"
authors:
  - name: Jane Doe
    email: "janedoe@mockuniversity.edu"
    affiliations:
      - name: University of Mock 
        department: Department of Something 
        city: Miami
        state: Florida
        country: United States
  - name: Author 2
    email: "xxxxxx"
    affiliations:
      - name: xxxxx
        department: xxxxxx
        city: xxxxx
        state: xxxxx
        country: xxxxxx
  - name: Additional Co-author(s)
    email: "xxxxxxx"
    affiliations:
      - name: xxxxx
        department: xxxxxx
        city: xxxx
        state: xxxxx
        country: xxxxxx

abstract: |
  The is the abstract section.  Ipsum leo porta – lacinia sed ac interdum nec vel ad. Elementum augue platea eleifend himenaeos nisl, viverra sem molestie. Hendrerit enim torquent litora fusce ultrices, magna, lacus id potenti! Imperdiet vulputate etiam conubia sem mi incep- tos. Quisque mollis viverra lacinia bibendum ultricies, dui est gravida tristique nascetur. Pellentesque id elementum com- modo pretium quisque purus mi taciti.

index-terms: 
  - Keyword 1
  - Keyword 2 
  - Keyword 3
  - Keyword 4
  - Keyword 5

format:
  ieee-typst: default
bibliography: references.bib
---
```{r}
#| echo: FALSE
library(lorem)
```

## Introduction
_Introduce the research topic, state the research problem, and outline the study's objectives. Provide background information to set the context. This is an exmaple in-text citation_ @netwok2020.
`r lorem::ipsum(paragraphs = 3)`


### Background
_Provide a brief review of the pertinent literature, highlighting the gaps your study aims to fill._
`r lorem::ipsum(paragraphs = 2)`


### Objectives
_State the specific research questions or hypotheses your study addresses._
`r lorem::ipsum(paragraphs = 2)`


## Methods
_Describe the methodological approach, detailing how the study was conducted, how data was collected, and how analyses were performed._
`r lorem::ipsum(paragraphs = 1)`


### Participants
_Describe the demographic characteristics of the study participants, including how they were selected, recruited, and any inclusion or exclusion criteria._
`r lorem::ipsum(paragraphs = 1)`


### Measures
_List the instruments or tools used to collect data, describing each measure's purpose and any relevant psychometric properties._
`r lorem::ipsum(paragraphs = 2)`


### Analytic Plan
_Detail the statistical tests or models employed to analyze the data, including any software used._
`r lorem::ipsum(paragraphs = 1)`


## Results
Present the findings of the study, supported by statistical analysis, tables, and figures as necessary.
`r lorem::ipsum(paragraphs = 3)`


### [Subsection Title]
_Present specific findings related to a particular aspect of the study, supported by data._
`r lorem::ipsum(paragraphs = 1)`


### [Subsection Title]
_Discuss another set of findings, providing details on the analysis and interpretation._
`r lorem::ipsum(paragraphs = 1)`


## Discussion
_Interpret the results, discussing their implications in the context of existing literature. Address the study's limitations and suggest directions for future research._
`r lorem::ipsum(paragraphs = 3)`


### Limitations
_Acknowledge any limitations of your study and their potential impact on the findings._
`r lorem::ipsum(paragraphs = 1)`


### Future Directions
_Suggest areas for future research that could build on your findings or address limitations._
`r lorem::ipsum(paragraphs = 1)`


## Conclusion
_Summarize the main findings and their implications. Conclude with a statement that reflects the significance of the study and its contributions to the field._
`r lorem::ipsum(paragraphs = 1)`


## Acknowledgments
_Acknowledge anyone who contributed to the research but does not meet authorship criteria, along with any funding sources._
`r lorem::ipsum(paragraphs = 1)`


## Appendices
_Include any additional material that is pertinent to the study but would be too distracting or bulky to include in the main body of the manuscript._
`r lorem::ipsum(paragraphs = 1)`



